baseURL = 'https://elotechy.github.io/'  # or your actual URL
languageCode = 'en-us'
title = 'elotechy'
theme = 'PaperMod'

[params]
  description = "PhD Researcher | Machine Learning Engineer | AI for Engineering & Public Safety"
  author = "Eloghosa Anderson Ikponmwoba"
  
  [params.profileMode]
    enabled = true
    title = "Eloghosa Anderson Ikponmwoba"
    subtitle = "PhD Researcher | Machine Learning Engineer"
    imageUrl = "/images/elo_cropped.jpg"  # Add your profile picture here
    imageWidth = 300
    imageHeight = 300
    imageTitle = "Eloghosa Ikponmwoba"
    
    [[params.profileMode.buttons]]
      name = "Blog"
      url = "/blog"
    
    [[params.profileMode.buttons]]
      name = "Portfolio"
      url = "/portfolio"
    
    [[params.profileMode.buttons]]
      name = "CV"
      url = "/cv"
    
    [[params.profileMode.buttons]]
      name = "Contact"
      url = "mailto:eloghosaefficiency@gmail.com"

  # Social links
  [[params.socialIcons]]
    name = "email"
    url = "mailto:eloghosaefficiency@gmail.com"
  
  [[params.socialIcons]]
    name = "linkedin"
    url = "https://linkedin.com/in/eloghosa-ikponmwoba"
  
  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/elotechy"  # Add your GitHub username
  
  [[params.socialIcons]]
    name = "googlescholar"
    url = "https://scholar.google.com/citations?user=_UKj_poAAAAJ&hl=en"  # Add your Google Scholar

# Menu configuration
[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 2

  [[menu.main]]
    name = "Portfolio"
    url = "/portfolio/"
    weight = 3

  [[menu.main]]
    name = "CV"
    url = "/cv/"
    weight = 4

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 5

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true