baseURL = 'https://elotechy.com/'
languageCode = 'en-us'
title = 'elotechy'
theme = 'PaperMod'
relativeURLs = false

# Google Analytics 
[services]
  [services.googleAnalytics]
    id = "G-FJDRKNE2L9"  # Replace with your Google Analytics Tracking ID

[params]
  description = "PhD Researcher | Machine Learning Engineer | AI for Engineering & Public Safety"
  author = "Eloghosa Anderson Ikponmwoba"
  env = "production"
  [params.profileMode]
    enabled = true
    title = "Eloghosa Anderson Ikponmwoba"
    subtitle = "PhD Researcher | Machine Learning Engineer"
    imageUrl = "images/elo_cropped.jpg"  # Add your profile picture here
    imageWidth = 300
    imageHeight = 300
    imageTitle = "Eloghosa Ikponmwoba"
    
    [[params.profileMode.buttons]]
      name = "Blog"
      url = "/elo-webpage/blog/"
    
    [[params.profileMode.buttons]]
      name = "Portfolio"
      url = "/elo-webpage/portfolio/"
    
    [[params.profileMode.buttons]]
      name = "CV"
      url = "/elo-webpage/cv/"
    
    [[params.profileMode.buttons]]
      name = "Contact"
      url = "mailto:eloghosaefficiency@gmail.com"

  ShowRssButtonInSectionTermList = true

  # Social links
  [[params.socialIcons]]
    name = "email"
    url = "mailto:eloghosaefficiency@gmail.com"
  
  [[params.socialIcons]]
    name = "linkedin"
    url = "https://linkedin.com/in/eloghosa-ikponmwoba"
  
  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/elotechy"  # Add your GitHub username
  
  [[params.socialIcons]]
    name = "googlescholar"
    url = "https://scholar.google.com/citations?user=_UKj_poAAAAJ&hl=en"  # Add your Google Scholar

  # RSS description
  rssDescription = "PhD Researcher | ML Engineer - Writing about AI, Engineering, and Research"
  ShowRssButtonInSectionTermList = true

[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true
    respectDoNotTrack = true

# Menu configuration
[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 2

  [[menu.main]]
    name = "Portfolio"
    url = "/portfolio/"
    weight = 3

  [[menu.main]]
    name = "About"
    url = "/cv/"
    weight = 4

  [[menu.main]]
    name = "Subscribe"
    url = "/subscribe/"
    weight = 5

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true



# RSS Configuration
[outputs]
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML"]
  section = ["HTML", "RSS"]

[outputFormats]
  [outputFormats.RSS]
    mediatype = "application/rss"
    baseName = "feed"  # This creates feed.xml instead of index.xml
    isPlainText = false

# RSS Params
  
[author]
  name = "Eloghosa Anderson Ikponmwoba"
  email = "eloghosaefficiency@gmail.com"

# Copyright notice in RSS
copyright = "© 2025 Eloghosa Anderson Ikponmwoba"